version: "3.8"
services:
  postgres:
    container_name: postgres_container
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres
      
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
    
volumes:
    postgres:
    pgadmin:
